services:
  - type: web
    name: anisa-senior-high-school
    runtime: node
    plan: free
    buildCommand: "echo 'Build successful'"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
